name: set-evironment
author: bekurin
description: 'setting environment in github action'
inputs:
  REF_TYPE:
    description: 'branch or tag'
    required: true
    default: 'branch'
  BASE_REF:
    description: 'develop or main'
    required: true
    default: 'develop'
outputs:
  environment:
    description: 'Get env'
    value: ${{ steps.set-env.outputs.environment }}

runs:
  using: composite
  steps:
    - name: set env
      id: set-env
      shell: bash
      run: |
        if [[ ${{ inputs.REF_TYPE }} == 'tag' ]]; then
          echo 'environment=qa' >> $GITHUB_OUTPUT
          exit 0
        fi
        
        if [[ ${{ inputs.REF_TYPE }} == 'branch' ]]; then
          echo 'environment=develop' >> $GITHUB_OUTPUT
          if [[ ${{ inputs.BASE_REF }} == 'main' ]]; then
            echo 'environment=main' >> $GITHUB_OUTPUT
          fi
        fi
    - name: check output
      shell: bash
      run: |
        echo ${{ steps.set-env.outputs.environment }}
